eduardo:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - base_to_shoulder
      - shoulder_upper_arm
      - upper_lower_arm
      - lower_arm_hand
      - comb
      - comb_end
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []
  arm_position_controller:
    type: position_controllers/JointPositionController
    joints:
      - base_to_shoulder
      - shoulder_upper_arm
      - upper_lower_arm
      - lower_arm_hand
      - comb
    gains:
      base_to_shoulder:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      shoulder_upper_arm:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      upper_lower_arm:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      lower_arm_hand:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      comb:
        p: 100
        d: 1
        i: 1
        i_clamp: 1